### PR TITLE
Update to rack 2.1.4

### PR DESCRIPTION
**Pull request by dmann**

### CODE REVIEW

**Comment by dmlond** [comment]
looks like a test failed

**Comment by dmann** [comment]
@dmlond Indeed it does. Odd, because everything passed when I ran the entire suite locally...

**Comment by dmann** [comment]
@dmlond Ok, good to go now. Please ignore the `codecove/project` check, it does not seem to be configured properly. The `codecove/patch` check passes and that's what really matters.

**Review by dmlond — APPROVED** [review]
👍

**Pull request merged**
