### PR TITLE
DDS-744 rename search provenance endpoint

### PR DESCRIPTION
**Pull request by dmlond**
from /search/provenance/was_generated_by to /search/provenance/origin

### CODE REVIEW

**Review by dmann — APPROVED** [review]
🥇

**Comment by caseychoiniere** [comment]
This is a breaking change. Not sure if anyone is using this endpoint but me but if so you might want to let them know. I just spent 30 minutes trying to figure out what I broke :/

**Comment by jonturneratduke** [comment]
I'll ping Dan & John @ GCB to give 'em a "head's-up."

**Comment by dmlond** [comment]
@mgardnerpsu @jonturneratduke @caseychoiniere what is the best way for us address this? 

The Change Log in apiary was published for this on [October 17](https://apidev.dataservice.duke.edu/apidocs/api_basics.html#header-17-oct-2016).

We need some way of warning casey and other client developers when we deploy the changes. It's a lot to keep track of :(

**Pull request merged**
